# Generated by Django 4.1 on 2022-08-22 01:28

import apps.phone_book.models
import birthday.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of tag', max_length=200, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='This is the name of the contact', max_length=200, verbose_name='Contact name')),
                ('contact_birthday_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('contact_birthday', birthday.fields.BirthdayField(blank=True, help_text='This is the birthday of the contact', max_length=150, null=True, verbose_name='Birthday')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='This is a phone number', max_length=128, region=None, unique=True, verbose_name='Phone number')),
                ('url_profile_linkedin', models.URLField(blank=True, help_text='Link to LinkedIn Profile', null=True, validators=[apps.phone_book.models.RequireLinkToLinkedinProfile()], verbose_name='LinkedIn Url profile')),
                ('nick_linkedin', models.CharField(blank=True, help_text='Automatically generated from LinkedIn Url profile', max_length=200, null=True, verbose_name='linkedin Nick')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='Contact_related_many_to_many_items', to='phone_book.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_details_name', models.CharField(help_text='Name of contact details', max_length=200, verbose_name='Contact details name')),
                ('contact_details', models.CharField(help_text='This is the contact details', max_length=200, verbose_name='Contact details')),
                ('id_phone_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_book.phonebook', verbose_name='Contact')),
            ],
        ),
    ]
