# Generated by Django 4.1 on 2022-08-16 00:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='This is the name of the contact', max_length=200, verbose_name='Contact name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='This is a phone number', max_length=128, region=None, unique=True, verbose_name='Phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
