# Generated by Django 4.1 on 2022-09-15 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("middleware_logger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="last_visit",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 9, 15, 1, 25, 21, 751887, tzinfo=datetime.timezone.utc),
                null=True,
                verbose_name="Last Visit",
            ),
        ),
    ]
