# Generated by Django 4.1 on 2022-09-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionAll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_key",
                    models.CharField(help_text="Key of Session", max_length=1000, verbose_name="Session key"),
                ),
                ("count_of_visits", models.PositiveSmallIntegerField()),
                ("last_visit", models.DateTimeField()),
            ],
        ),
    ]
